### ISSUE TITLE
Coverage upload task with multiple git repositories in project?

### ISSUE THREAD

**Issue by SDohle** [cqse/Teamscale-AzureDevOps-Extension#31]
Hi,

i want to upload test coverage to a TeamScale project with multiple git connectors.
But how to specify the git repository in the task?

- TeamScale 6.5
- AzureDevops Server 2020
- TeamScale Extension 1.2.7

**Comment by rottkit** [comment]
Hi @SDohle,

Specifying the Git Repository in the Upload Task should not be necessary and is thus not possible.
Teamscale uses the file path(s) as in the coverage report and assigns the coverage to a file within the Teamscale analysis scope that has the longest matching path suffix.

Can you please further elaborate on the issue that you experience? Have you tried uploading the report and did the coverage not appear or was it attached to wrong files? In case of file paths appearing in the report can not be matched to a file analysed by Teamscale or can be matched to multiple files (e.g., due to same path and folder structuring in different connected `git`s), I would expect a Worker Log entry to be generated (by the `IntegrateImportedAnalysisResultsTrigger`). Can you please provide whether there are warnings logged?

Sorry for the delay in answering your question. Please kindly consider using our official support via support@teamscale.com or https://www.cqse.eu/en/teamscale/support/

Thanks and best regards

**Comment by SDohle** [comment]
Hi,
I am still struggling with problems generating the coverage in all the repositories. So i currently have no idea how Teamascale handles the uploads. I wil contact you if I am at this point and have problems.

One last question: Is there a way to customize the upload message? Or any other field visible in the 'External upload UI' in teamscale to show the repository? Thanks for your help.

Best regards 
Steffen

**Comment by rottkit** [comment]
Hi @SDohle,

If I understand correctly the struggle is the coverage collection outside of Teamscale, right? Of course, please come back to us if there is any problem uploading the reports to Teamscale.

The _upload message_ as displayed in the Teamscale Activity perspective is not changeable in the Azure DevOps Extension but fixed to "$PARTITION Upload (Build $BUILD_ID)". If you would benefit from this option, you could create an Issue requesting this feature.

You have the possibility to change the _partition_ and the _report's format_ in the extension. _Code Date_ and _Branch_ are set according to the build run. See also the attached Screenshot (left: Upload Form in Teamscale; right: Options in Azure DevOps Plugin)

![Screenshot 2021-02-02 at 16 13 45](https://user-images.githubusercontent.com/35423135/106620506-ed302f80-6571-11eb-8535-8905b4f17ef6.png)

I close this issue for now. If I can help you any further, please do not hesitate reopening it or contacting support@teamscale.com.
